version: '3.9'

services:
  mongo:
    image: mongo:5.0
    ports:
      - "27017:27017"
    volumes:
      - ./.mongo:/data/db
  mysql:
    image: mysql:5.7.37
    ports:
      - "3306:3306"
    volumes:
      - ./.mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=S3cret
      - MYSQL_DATABASE=om_db
